name: NHSHackday
markdown: rdiscount
rdiscount:
    extensions:
        - generate_toc
    toc_token: "!!!TOC"
pygments: true
previous:
    - Jan 2015 Cardiff
    - Sep 2014 Leeds
    - Jan 2014 Cardiff
    - Nov 2013 Cambridge
    - May 2013 London
    - Jan 2013 Oxford
    - Sep 2012 Liverpool
    - May 2012 London
nexter-event: 
    location: "Manchester this autumn"
next-event:
    date: "30 & 31 January 2016"
    location: "Cardiff"
    venue: "Cardiff, Wales"
    signup: "http://www.eventbrite.co.uk/e/nhs-hack-day-cardiff-2016-tickets-19078337822"

