name: NHSHackday
markdown: redcarpet
pygments: true
previous:
    - Sep 2014 Leeds
    - Jan 2014 Cardiff
    - Nov 2013 Cambridge
    - May 2013 London
    - Jan 2013 Oxford
    - Sep 2012 Liverpool
    - May 2012 London
next-event:
    date: January 2015
    location: Cardiff
    venue:  ""
    xsignup: https://www.eventbrite.co.uk/e/nhs-hack-day-leeds-tickets-12825865509
