name: NHSHackday
markdown: redcarpet
pygments: true
previous:
    - Jan 2014 Cardiff
    - Nov 2013 Cambridge
    - May 2013 London
    - Jan 2013 Oxford
    - Sep 2012 Liverpool
    - May 2012 London
next-event:
    date: 27th-28th of Sep 2014
    location: "Leeds, England, Europe"
    venue:  "Retrograde Academy, 23 The Calls Leeds LS2 7EH"
    signup: https://www.eventbrite.co.uk/e/nhs-hack-day-leeds-tickets-12825865509
