name: NHSHackday
markdown: rdiscount
rdiscount:
    extensions:
        - generate_toc
    toc_token: "!!!TOC"
pygments: true
source: source

previous:
    - Sep 2014 Leeds
    - Jan 2014 Cardiff
    - Nov 2013 Cambridge
    - May 2013 London
    - Jan 2013 Oxford
    - Sep 2012 Liverpool
    - May 2012 London
next-event:
    date: "24th-25th January 2015"
    location: Cardiff
    venue: "Hadyn Ellis Building, Cardiff University School of Medicine, CF24 4HQ"
    signup: "https://www.eventbrite.co.uk/e/nhs-hack-day-cardiff-2015-tickets-13564701387"
