name: NHSHackday
markdown: rdiscount
rdiscount:
    extensions:
        - generate_toc
    toc_token: "!!!TOC"
pygments: true
previous:
    - Jan 2015 Cardiff
    - Sep 2014 Leeds
    - Jan 2014 Cardiff
    - Nov 2013 Cambridge
    - May 2013 London
    - Jan 2013 Oxford
    - Sep 2012 Liverpool
    - May 2012 London
next-event:
    date: "May 2015"
    location: London
    venue: "tbc asap"
    signup: ""
