name: NHSHackday
markdown: rdiscount
rdiscount:
    extensions:
        - generate_toc
    toc_token: "!!!TOC"
pygments: true
previous:
    - January 2016 Cardiff
    - September 2015 Leeds
    - May 2015 London
    - Jan 2015 Cardiff
    - Sep 2014 Leeds
    - Jan 2014 Cardiff
    - Nov 2013 Cambridge
    - May 2013 London
    - Jan 2013 Oxford
    - Sep 2012 Liverpool
    - May 2012 London
next-event:
    date: "14 & 15 May 2016"
    location: "London"
    venue: "KCL Strand Campus, London WC2R 2LS"
    signup: "https://www.eventbrite.co.uk/e/nhs-hack-day-london-2016-tickets-23403024075"

